### ISSUE TITLE
files

### ISSUE THREAD

**Issue by 123wnk** [tyang816/ProtREM#2]
Would you please show the URL list below
# unzip fasta sequence files
tar -xzf aa_seq.tar.gz
# unzip pdb structure files
tar -xzf pdbs.tar.gz
# unzip structure sequence files
tar -xzf struc_seq.tar.gz
# unzip DMS substitution csv files
tar -xzf substitutions.tar.g

**Comment by tyang816** [comment]
Sorry for the misleading script, I will update the README soon.
