### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Lee951108** [tyang816/ProtREM#4]
Great job! I meet some problems.
1. I got an pip error when i use conda, evcouplings==0.2.0 is not available, and the torch-cluster,torch-sparse,torch-scatter all got error.
2.When i run evcouplings to get aa_aln，i got an error, if i add the plmc to PATH can solve this?
3. The yml file set the prefix, is that caused the question 2? 

![image](https://github.com/user-attachments/assets/104a7d2f-49da-4fc3-bc8e-b122749d5b98)

Traceback (most recent call last):
  File "/share/org/CAASZHUJK/caas_lws/miniconda3/envs/protrem/lib/python3.10/site-packages/evcouplings/utils/system.py", line 65, in run
    with subprocess.Popen(
  File "/share/org/CAASZHUJK/caas_lws/miniconda3/envs/protrem/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/share/org/CAASZHUJK/caas_lws/miniconda3/envs/protrem/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tanyang/plmc/bin/plmc'

**Comment by tyang816** [comment]
1. pip install https://github.com/debbiemarkslab/EVcouplings/archive/develop.zip

**Comment by tyang816** [comment]
2. Plz install plmc, and change the file path in [here](https://github.com/tyang816/ProtREM/blob/565ad5426d910db5396fe274f5125018e3a715f4/src/single_config_monomer.txt#L418C5-L418C38)

**Comment by Lee951108** [comment]
Thanks for your timing reply! I confused with the install program. I need to run the conda before install EVcoupling ? Because the conda faces pip install fail

**Comment by tyang816** [comment]
Could you please provide the error information? If you already have an environment, just install the evcouplings and plmc

**Comment by tyang816** [comment]
emmm, maybe undegrade the python version to 3.9?

**Comment by Lee951108** [comment]
I tried ,but fails
![image](https://github.com/user-attachments/assets/05bd812c-0981-4ba4-97d7-75c4e70df061)

**Comment by tyang816** [comment]
let me check again plz... Sorry for the problem😥

**Comment by Lee951108** [comment]
I‘m very interested in this work. If the problem is solved, please let me know. Thank you very much!

**Comment by tyang816** [comment]
I will rebuild the environment and contact you as soon as the bug is fixed.

**Comment by tyang816** [comment]
@Lee951108 Hi,
I have updated the environment file, plz have a try!

**Comment by Lee951108** [comment]
![image](https://github.com/user-attachments/assets/630c94d4-24da-4634-bcc6-9306e7d691de)
Hi, I run conda env create -f environment.yml still got pip fail

**Comment by tyang816** [comment]
ok... do you have an environment already? Just use your environment plz and install the hmmer and evcoplings

**Comment by Lee951108** [comment]
Yes I install the hmmer and evcoplings. I will test the get_aa_seq_aln_a2m.sh and select_aa_seq_aln_a2m.sh
Thanks a lot , if something goes wrong i will let you know!

**Comment by tyang816** [comment]
Great! Thank you for following our work!

**Comment by Lee951108** [comment]
I run get_struc_seq.py to turn pdb file to seq, error hits packages in conda program not installed. Based on the pip install error maybe it is necessary to be solved in the first place ?

**Comment by Lee951108** [comment]
I manually install packages, it runs well so far.

**Comment by tyang816** [comment]
Great! Sorry for the problem agagin...
